import type { Metadata } from "next";
import { Geist, Geist_Mono, Julius_Sans_One } from "next/font/google";
import "./globals.css";
import { UIProvider } from "./UIProvider/contextUI";
import { LateralBar } from "./components/lateralbar";
import { Sidebar } from "./components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const JuliusSansOne = Julius_Sans_One({
weight:"400",
variable:"--Julius-Sans-One"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${JuliusSansOne.variable} antialiased
        grid grid-cols-[60px_1fr_60px]`}
      >
        <UIProvider>

        <Sidebar/>
        {children}
        <LateralBar/>
        </UIProvider>
      </body>
    </html>
  );
}
