import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Julius_Sans_One,
  Thasadith,
  Alan_Sans
} from "next/font/google";
import "./globals.css";
import { UIProvider } from "./UIProvider/contextUI";
import { ContextProvider } from "./context/context";
import { LateralBar } from "./components/lateralbar";
import { Sidebar } from "./components/sidebar";
import { NavbarMobile } from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const AlanSans = Alan_Sans({
  weight: "500",
  variable: "--Alan-Sans",
})

const JuliusSansOne = Julius_Sans_One({
  weight: "400",
  variable: "--Julius-Sans-One",
});

const thasadith = Thasadith({
  weight: "400",
  variable: "--Thasadith",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${JuliusSansOne.variable} ${thasadith.variable} ${AlanSans.variable} antialiased
        relative  bg-[url('/backgroundApp-hight.jpg')] bg-no-repeat bg-cover bg-fixed  `}
      >
        <ContextProvider>
          <UIProvider>
            <NavbarMobile/>
            <Sidebar />
            <div className="pl-8.75 pr-8.75">{children}</div> 
            <LateralBar />
          </UIProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
